name: cbx
base: core22
version: 'git'
summary: A TUI application for inspecting CBOR data
confinement: strict
grade: stable

apps:
  cbx:
    command: bin/cbx
    plugs: [home, removable-media]

parts:
  cbx:
    plugin: rust
    source: .